apiVersion: v1
kind: Service
metadata:
  name: green-service
  labels:
    version: green
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: demo-app
    version: green